// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UploadService.Infrastructure.Persistence.Context;

#nullable disable

namespace UploadService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(UploadDbContext))]
    partial class UploadDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("upload")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UploadService.Domain.Entities.AnalysisRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("Status");

                    b.ToTable("analysis_requests", "upload");
                });

            modelBuilder.Entity("UploadService.Domain.Entities.AnalysisRequest", b =>
                {
                    b.OwnsOne("StorageLocation", "StorageLocation", b1 =>
                        {
                            b1.Property<Guid>("AnalysisRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BucketName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("storage_bucket");

                            b1.Property<string>("ObjectKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("storage_object_key");

                            b1.HasKey("AnalysisRequestId");

                            b1.ToTable("analysis_requests", "upload");

                            b1.WithOwner()
                                .HasForeignKey("AnalysisRequestId");
                        });

                    b.OwnsOne("UploadService.Domain.ValueObjects.FileHash", "FileHash", b1 =>
                        {
                            b1.Property<Guid>("AnalysisRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("file_hash");

                            b1.HasKey("AnalysisRequestId");

                            b1.ToTable("analysis_requests", "upload");

                            b1.WithOwner()
                                .HasForeignKey("AnalysisRequestId");
                        });

                    b.OwnsOne("UploadService.Domain.ValueObjects.FileMetadata", "FileMetadata", b1 =>
                        {
                            b1.Property<Guid>("AnalysisRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("content_type");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("file_name");

                            b1.Property<int>("FileType")
                                .HasColumnType("integer")
                                .HasColumnName("file_type");

                            b1.Property<long>("SizeInBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("size_in_bytes");

                            b1.HasKey("AnalysisRequestId");

                            b1.ToTable("analysis_requests", "upload");

                            b1.WithOwner()
                                .HasForeignKey("AnalysisRequestId");
                        });

                    b.Navigation("FileHash")
                        .IsRequired();

                    b.Navigation("FileMetadata")
                        .IsRequired();

                    b.Navigation("StorageLocation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
