// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProcessingService.Infrastructure.Persistence.Context;

#nullable disable

namespace ProcessingService.Infrastructure.Migrations
{
    [DbContext(typeof(ProcessingDbContext))]
    [Migration("20260426234611_InitialProcessingSchema")]
    partial class InitialProcessingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("processing")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProcessingService.Domain.Entities.AnalysisProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_request_id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiagramType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureDetails")
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("_componentsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("components");

                    b.Property<string>("_recommendationsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("recommendations");

                    b.Property<string>("_risksJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("risks");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRequestId")
                        .HasDatabaseName("ix_analysis_processes_analysis_request_id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("Status");

                    b.ToTable("analysis_processes", "processing");
                });

            modelBuilder.Entity("ProcessingService.Domain.Entities.AnalysisProcess", b =>
                {
                    b.OwnsOne("ProcessingService.Domain.ValueObjects.ExtractedText", "ExtractedText", b1 =>
                        {
                            b1.Property<Guid>("AnalysisProcessId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("extracted_text");

                            b1.HasKey("AnalysisProcessId");

                            b1.ToTable("analysis_processes", "processing");

                            b1.WithOwner()
                                .HasForeignKey("AnalysisProcessId");
                        });

                    b.OwnsOne("ProcessingService.Domain.ValueObjects.ProcessingResultSummary", "ResultSummary", b1 =>
                        {
                            b1.Property<Guid>("AnalysisProcessId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Overview")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("summary_overview");

                            b1.Property<bool>("RequiresManualReview")
                                .HasColumnType("boolean")
                                .HasColumnName("summary_requires_manual_review");

                            b1.Property<int>("TotalComponents")
                                .HasColumnType("integer")
                                .HasColumnName("summary_total_components");

                            b1.Property<int>("TotalRecommendations")
                                .HasColumnType("integer")
                                .HasColumnName("summary_total_recommendations");

                            b1.Property<int>("TotalRisks")
                                .HasColumnType("integer")
                                .HasColumnName("summary_total_risks");

                            b1.Property<string>("Warnings")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("summary_warnings");

                            b1.HasKey("AnalysisProcessId");

                            b1.ToTable("analysis_processes", "processing");

                            b1.WithOwner()
                                .HasForeignKey("AnalysisProcessId");
                        });

                    b.OwnsOne("ProcessingService.Domain.ValueObjects.SourceFileLocation", "SourceFileLocation", b1 =>
                        {
                            b1.Property<Guid>("AnalysisProcessId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BucketName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("source_bucket");

                            b1.Property<string>("ObjectKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("source_object_key");

                            b1.HasKey("AnalysisProcessId");

                            b1.ToTable("analysis_processes", "processing");

                            b1.WithOwner()
                                .HasForeignKey("AnalysisProcessId");
                        });

                    b.Navigation("ExtractedText");

                    b.Navigation("ResultSummary");

                    b.Navigation("SourceFileLocation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
